/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-12-16 01:06:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<!--[if lt IE 7]><html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"ko\"> <![endif]-->\n");
      out.write("<!--[if (IE 7)&!(IEMobile)]><html class=\"no-js lt-ie9 lt-ie8\" lang=\"ko\"><![endif]-->\n");
      out.write("<!--[if (IE 8)&!(IEMobile)]><html class=\"no-js lt-ie9\" lang=\"ko\"><![endif]-->\n");
      out.write("<!--[if (IE 9)]><html class=\"no-js ie9\" lang=\"ko\"><![endif]-->\n");
      out.write("<!--[if gt IE 8]><!--><html lang=\"ko\"> <!--<![endif]-->\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("<meta name=\"description\" content=\"Insert Your Site Description\" /> \n");
      out.write("\n");
      out.write("<!-- Mobile Specifics -->\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"HandheldFriendly\" content=\"true\"/>\n");
      out.write("<meta name=\"MobileOptimized\" content=\"320\"/>   \n");
      out.write("\n");
      out.write("<!-- Mobile Internet Explorer ClearType Technology -->\n");
      out.write("<!--[if IEMobile]>  <meta http-equiv=\"cleartype\" content=\"on\">  <![endif]-->\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link href=\"_include/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Main Style -->\n");
      out.write("<link href=\"_include/css/main.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Supersized -->\n");
      out.write("<link href=\"_include/css/supersized.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"_include/css/supersized.shutter.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- FancyBox -->\n");
      out.write("<link href=\"_include/css/fancybox/jquery.fancybox.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Font Icons -->\n");
      out.write("<link href=\"_include/css/fonts.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Shortcodes -->\n");
      out.write("<link href=\"_include/css/shortcodes.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Responsive -->\n");
      out.write("<link href=\"_include/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"_include/css/responsive.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Supersized -->\n");
      out.write("<link href=\"_include/css/supersized.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"_include/css/supersized.shutter.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Google Font -->\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("<!-- Fav Icon -->\n");
      out.write("<link rel=\"shortcut icon\" href=\"#\">\n");
      out.write("\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"#\">\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"#\">\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"#\">\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"#\">\n");
      out.write("\n");
      out.write("<!-- Modernizr -->\n");
      out.write("<script src=\"_include/js/modernizr.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Analytics -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("  var _gaq = _gaq || [];\n");
      out.write("  _gaq.push(['_setAccount', 'Insert Your Code']);\n");
      out.write("  _gaq.push(['_trackPageview']);\n");
      out.write("\n");
      out.write("  (function() {\n");
      out.write("    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n");
      out.write("    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n");
      out.write("    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n");
      out.write("  })();\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<!-- End Analytics -->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- This section is for Splash Screen -->\n");
      out.write("<div class=\"ole\">\n");
      out.write("<section id=\"jSplash\">\n");
      out.write("\t<div id=\"circle\"></div>\n");
      out.write("</section>\n");
      out.write("</div>\n");
      out.write("<!-- End of Splash Screen -->\n");
      out.write("\n");
      out.write("<!-- Homepage Slider -->\n");
      out.write("<div id=\"home-slider\">\t\n");
      out.write("    <div class=\"overlay\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"slider-text\">\n");
      out.write("    \t<div id=\"slidecaption\"></div>\n");
      out.write("    </div>   \n");
      out.write("\t\n");
      out.write("\t<div class=\"control-nav\">\n");
      out.write("        <a id=\"prevslide\" class=\"load-item\"><i class=\"font-icon-arrow-simple-left\"></i></a>\n");
      out.write("        <a id=\"nextslide\" class=\"load-item\"><i class=\"font-icon-arrow-simple-right\"></i></a>\n");
      out.write("        <ul id=\"slide-list\"></ul>\n");
      out.write("        \n");
      out.write("        <a id=\"nextsection\" href=\"#work\"><i class=\"font-icon-arrow-simple-down\"></i></a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- End Homepage Slider -->\n");
      out.write("\n");
      out.write("<!-- Header -->\n");
      out.write("<header>\n");
      out.write("    <div class=\"sticky-nav\">\n");
      out.write("    \t<a id=\"mobile-nav\" class=\"menu-nav\" href=\"#menu-nav\"></a>\n");
      out.write("        \n");
      out.write("        <div id=\"logo\">\n");
      out.write("        \t<a id=\"goUp\" href=\"#home-slider\" title=\"Brushed | Responsive One Page Template\">Brushed Template</a>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <nav id=\"menu\">\n");
      out.write("        \t<ul id=\"menu-nav\">\n");
      out.write("            \t<li class=\"current\"><a href=\"#home-slider\">Home</a></li>\n");
      out.write("                <li><a href=\"#work\">Our Work</a></li>\n");
      out.write("                <li><a href=\"#about\">About Us</a></li>\n");
      out.write("                <li><a href=\"#contact\">Contact</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"shortcodes.html\" class=\"external\">Shortcodes</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("<!-- End Header -->\n");
      out.write("\n");
      out.write("<!-- Our Work Section -->\n");
      out.write("<div id=\"work\" class=\"page\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("    \t<!-- Title Page -->\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"span12\">\n");
      out.write("                <div class=\"title-page\">\n");
      out.write("                    <h2 class=\"title\">Our Work</h2>\n");
      out.write("                    <h3 class=\"title-description\">Check Out Our Projects on <a href=\"#\">Dribbble</a>.</h3>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- End Title Page -->\n");
      out.write("        \n");
      out.write("        <!-- Portfolio Projects -->\n");
      out.write("        <div class=\"row\">\n");
      out.write("        \t<div class=\"span3\">\n");
      out.write("            \t<!-- Filter -->\n");
      out.write("                <nav id=\"options\" class=\"work-nav\">\n");
      out.write("                    <ul id=\"filters\" class=\"option-set\" data-option-key=\"filter\">\n");
      out.write("                    \t<li class=\"type-work\">Type of Work</li>\n");
      out.write("                        <li><a href=\"#filter\" data-option-value=\"*\" class=\"selected\">All Projects</a></li>\n");
      out.write("                        <li><a href=\"#filter\" data-option-value=\".java\">java</a></li>\n");
      out.write("                        <li><a href=\"#filter\" data-option-value=\".web\">web</a></li>\n");
      out.write("                        <li><a href=\"#filter\" data-option-value=\".android\">android</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- End Filter -->\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"span9\">\n");
      out.write("            \t<div class=\"row\">\n");
      out.write("                \t<section id=\"projects\">\n");
      out.write("                    \t<ul id=\"thumbs\">\n");
      out.write("                        \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 java\">\n");
      out.write("                            \t<!-- Fancybox - Gallery Enabled - Title - Full Image -->\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"java1\" href=\"_include/img/work/full/image-01-full.jpg\">\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-01.jpg\" alt=\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                            \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 java\">\n");
      out.write("                            \t<!-- Fancybox - Gallery Enabled - Title - Full Image -->\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"java2\" href=\"_include/img/work/full/image-02-full.jpg\">\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-02.jpg\" alt=\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                            \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 web\">\n");
      out.write("                            \t<!-- Fancybox - Gallery Enabled - Title - Full Image -->\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"web1\" href=\"_include/img/work/full/image-03-full.jpg\">\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-03.jpg\" alt=\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                            \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 android\">\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"android1\" href=\"_include/img/work/full/image-05-full.jpg>\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-08.jpg\" alt=\"android1\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                            \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 web\">\n");
      out.write("                            \t<!-- Fancybox - Gallery Enabled - Title - Full Image -->\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"web2\" href=\"_include/img/work/full/image-04-full.jpg\">\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-04.jpg\" alt=\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                            \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 web\">\n");
      out.write("                            \t<!-- Fancybox - Gallery Enabled - Title - Full Image -->\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"web3\" href=\"_include/img/work/full/image-05-full.jpg\">\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-05.jpg\" alt=\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                            \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 android\">\n");
      out.write("                            \t<!-- Fancybox Media - Gallery Enabled - Title - Link to Video -->\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"android2\" href=\"_include/img/work/full/image-05-full.jpg\">\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-09.jpg\" alt=\"android\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                            \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 java\">\n");
      out.write("                            \t<!-- Fancybox - Gallery Enabled - Title - Full Image -->\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"java3\" href=\"_include/img/work/full/image-06-full.jpg\">\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-06.jpg\" alt=\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                            \n");
      out.write("\t\t\t\t\t\t\t<!-- Item Project and Filter Name -->\n");
      out.write("                        \t<li class=\"item-thumbs span3 java\">\n");
      out.write("                            \t<!-- Fancybox - Gallery Enabled - Title - Full Image -->\n");
      out.write("                            \t<a class=\"hover-wrap fancybox\" data-fancybox-group=\"gallery\" title=\"java4\" href=\"_include/img/work/full/image-07-full.jpg\">\n");
      out.write("                                \t<span class=\"overlay-img\"></span>\n");
      out.write("                                    <span class=\"overlay-img-thumb font-icon-plus\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <!-- Thumb Image and Description -->\n");
      out.write("                                <img src=\"_include/img/work/thumbs/image-07.jpg\" alt=\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.\">\n");
      out.write("                            </li>\n");
      out.write("                        \t<!-- End Item Project -->\n");
      out.write("                        </ul>\n");
      out.write("                    </section>\n");
      out.write("                    \n");
      out.write("            \t</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- End Portfolio Projects -->\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- End Our Work Section -->\n");
      out.write("\n");
      out.write("<!-- About Section -->\n");
      out.write("<div id=\"about\" class=\"page-alternate\">\n");
      out.write("<div class=\"container\">\n");
      out.write("    <!-- Title Page -->\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"span12\">\n");
      out.write("            <div class=\"title-page\">\n");
      out.write("                <h2 class=\"title\">About Us</h2>\n");
      out.write("                <h3 class=\"title-description\">Learn About our Team &amp; Culture.</h3>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- End Title Page -->\n");
      out.write("    \n");
      out.write("    <!-- People -->\n");
      out.write("    <div class=\"row\">\n");
      out.write("    \t\n");
      out.write("        <!-- Start Profile -->\n");
      out.write("    \t<div class=\"span4 profile\">\n");
      out.write("        \t<div class=\"image-wrap\">\n");
      out.write("                <div class=\"hover-wrap\">\n");
      out.write("                    <span class=\"overlay-img\"></span>\n");
      out.write("                    <span class=\"overlay-text-thumb\">CTO/Founder</span>\n");
      out.write("                </div>\n");
      out.write("                <img src=\"_include/img/profile/profile-01.jpg\" alt=\"John Doe\">\n");
      out.write("            </div>\n");
      out.write("            <h3 class=\"profile-name\">John Doe</h3>\n");
      out.write("            <p class=\"profile-description\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac augue at erat <a href=\"#\">hendrerit dictum</a>. \n");
      out.write("            Praesent porta, purus eget sagittis imperdiet, nulla mi ullamcorper metus, id hendrerit metus diam vitae est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>\n");
      out.write("            \t\n");
      out.write("            <div class=\"social\">\n");
      out.write("            \t<ul class=\"social-icons\">\n");
      out.write("                \t<li><a href=\"#\"><i class=\"font-icon-social-twitter\"></i></a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"font-icon-social-dribbble\"></i></a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"font-icon-social-facebook\"></i></a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- End Profile -->\n");
      out.write("        \n");
      out.write("        <!-- Start Profile -->\n");
      out.write("    \t<div class=\"span4 profile\">\n");
      out.write("        \t<div class=\"image-wrap\">\n");
      out.write("                <div class=\"hover-wrap\">\n");
      out.write("                    <span class=\"overlay-img\"></span>\n");
      out.write("                    <span class=\"overlay-text-thumb\">Creative Director</span>\n");
      out.write("                </div>\n");
      out.write("                <img src=\"_include/img/profile/profile-02.jpg\" alt=\"Jane Helf\">\n");
      out.write("            </div>\n");
      out.write("            <h3 class=\"profile-name\">Jane Helf</h3>\n");
      out.write("            <p class=\"profile-description\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac augue at erat <a href=\"#\">hendrerit dictum</a>. \n");
      out.write("            Praesent porta, purus eget sagittis imperdiet, nulla mi ullamcorper metus, id hendrerit metus diam vitae est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>\n");
      out.write("            \t\n");
      out.write("            <div class=\"social\">\n");
      out.write("            \t<ul class=\"social-icons\">\n");
      out.write("                \t<li><a href=\"#\"><i class=\"font-icon-social-twitter\"></i></a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"font-icon-social-email\"></i></a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- End Profile -->\n");
      out.write("        \n");
      out.write("        <!-- Start Profile -->\n");
      out.write("    \t<div class=\"span4 profile\">\n");
      out.write("        \t<div class=\"image-wrap\">\n");
      out.write("                <div class=\"hover-wrap\">\n");
      out.write("                    <span class=\"overlay-img\"></span>\n");
      out.write("                    <span class=\"overlay-text-thumb\">Lead Designer</span>\n");
      out.write("                </div>\n");
      out.write("                <img src=\"_include/img/profile/profile-03.jpg\" alt=\"Joshua Insanus\">\n");
      out.write("            </div>\n");
      out.write("            <h3 class=\"profile-name\">Joshua Insanus</h3>\n");
      out.write("            <p class=\"profile-description\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac augue at erat <a href=\"#\">hendrerit dictum</a>. \n");
      out.write("            Praesent porta, purus eget sagittis imperdiet, nulla mi ullamcorper metus, id hendrerit metus diam vitae est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>\n");
      out.write("            \t\n");
      out.write("            <div class=\"social\">\n");
      out.write("            \t<ul class=\"social-icons\">\n");
      out.write("                \t<li><a href=\"#\"><i class=\"font-icon-social-twitter\"></i></a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"font-icon-social-linkedin\"></i></a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"font-icon-social-google-plus\"></i></a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"font-icon-social-vimeo\"></i></a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- End Profile -->\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    <!-- End People -->\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- End About Section -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Contact Section -->\n");
      out.write("<div id=\"contact\" class=\"page\">\n");
      out.write("<div class=\"container\">\n");
      out.write("    <!-- Title Page -->\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"span12\">\n");
      out.write("            <div class=\"title-page\">\n");
      out.write("                <h2 class=\"title\">Get in Touch</h2>\n");
      out.write("                <h3 class=\"title-description\">Weâre currently accepting new client projects. We look forward to serving you.</h3>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- End Title Page -->\n");
      out.write("    \n");
      out.write("    <!-- Contact Form -->\n");
      out.write("    <div class=\"row\">\n");
      out.write("    \t<div class=\"span9\">\n");
      out.write("        \n");
      out.write("        \t<form id=\"contact-form\" class=\"contact-form\" action=\"#\">\n");
      out.write("            \t<p class=\"contact-name\">\n");
      out.write("            \t\t<input id=\"contact_name\" type=\"text\" placeholder=\"Full Name\" value=\"\" name=\"name\" />\n");
      out.write("                </p>\n");
      out.write("                <p class=\"contact-email\">\n");
      out.write("                \t<input id=\"contact_email\" type=\"text\" placeholder=\"Email Address\" value=\"\" name=\"email\" />\n");
      out.write("                </p>\n");
      out.write("                <p class=\"contact-message\">\n");
      out.write("                \t<textarea id=\"contact_message\" placeholder=\"Your Message\" name=\"message\" rows=\"15\" cols=\"40\"></textarea>\n");
      out.write("                </p>\n");
      out.write("                <p class=\"contact-submit\">\n");
      out.write("                \t<a id=\"contact-submit\" class=\"submit\" href=\"#\">Send Your Email</a>\n");
      out.write("                </p>\n");
      out.write("                \n");
      out.write("                <div id=\"response\">\n");
      out.write("                \n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("         \n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"span3\">\n");
      out.write("        \t<div class=\"contact-details\">\n");
      out.write("        \t\t<h3>Contact Details</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">hello@brushed.com</a></li>\n");
      out.write("                    <li>(916) 375-2525</li>\n");
      out.write("                    <li>\n");
      out.write("                        Brushed Studio\n");
      out.write("                        <br>\n");
      out.write("                        5240 Vanish Island. 105\n");
      out.write("                        <br>\n");
      out.write("                        Unknow\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- End Contact Form -->\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- End Contact Section -->\n");
      out.write("\n");
      out.write("<!-- Twitter Feed -->\n");
      out.write("<div id=\"twitter-feed\" class=\"page-alternate\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("    \t<div class=\"row\">\n");
      out.write("            <div class=\"span12\">\n");
      out.write("                <div class=\"follow\">\n");
      out.write("                    <a href=\"https://twitter.com/Bluxart\" title=\"Follow Me on Twitter\" target=\"_blank\"><i class=\"font-icon-social-twitter\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                    \n");
      out.write("                <div id=\"ticker\" class=\"query\"> \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- End Twitter Feed -->\n");
      out.write("\n");
      out.write("<!-- Socialize -->\n");
      out.write("<div id=\"social-area\" class=\"page\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("    \t<div class=\"row\">\n");
      out.write("            <div class=\"span12\">\n");
      out.write("                <nav id=\"social\">\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"https://twitter.com/Bluxart\" title=\"Follow Me on Twitter\" target=\"_blank\"><span class=\"font-icon-social-twitter\"></span></a></li>\n");
      out.write("                        <li><a href=\"http://dribbble.com/Bluxart\" title=\"Follow Me on Dribbble\" target=\"_blank\"><span class=\"font-icon-social-dribbble\"></span></a></li>\n");
      out.write("                        <li><a href=\"http://forrst.com/people/Bluxart\" title=\"Follow Me on Forrst\" target=\"_blank\"><span class=\"font-icon-social-forrst\"></span></a></li>\n");
      out.write("                        <li><a href=\"http://www.behance.net/alessioatzeni\" title=\"Follow Me on Behance\" target=\"_blank\"><span class=\"font-icon-social-behance\"></span></a></li>\n");
      out.write("                        <li><a href=\"https://www.facebook.com/Bluxart\" title=\"Follow Me on Facebook\" target=\"_blank\"><span class=\"font-icon-social-facebook\"></span></a></li>\n");
      out.write("                        <li><a href=\"https://plus.google.com/105500420878314068694\" title=\"Follow Me on Google Plus\" target=\"_blank\"><span class=\"font-icon-social-google-plus\"></span></a></li>\n");
      out.write("                        <li><a href=\"http://www.linkedin.com/in/alessioatzeni\" title=\"Follow Me on LinkedIn\" target=\"_blank\"><span class=\"font-icon-social-linkedin\"></span></a></li>\n");
      out.write("                        <li><a href=\"http://themeforest.net/user/Bluxart\" title=\"Follow Me on ThemeForest\" target=\"_blank\"><span class=\"font-icon-social-envato\"></span></a></li>\n");
      out.write("                        <li><a href=\"http://zerply.com/Bluxart/public\" title=\"Follow Me on Zerply\" target=\"_blank\"><span class=\"font-icon-social-zerply\"></span></a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- End Socialize -->\n");
      out.write("\n");
      out.write("<!-- Footer -->\n");
      out.write("<footer>\n");
      out.write("\t<p class=\"credits\">&copy;2013 Brushed. <a href=\"http://themes.alessioatzeni.com/html/brushed/\" title=\"Brushed | Responsive One Page Template\">Brushed Template</a> by <a href=\"http://www.alessioatzeni.com/\" title=\"Alessio Atzeni | Web Designer &amp; Front-end Developer\">Alessio Atzeni</a></p>\n");
      out.write("</footer>\n");
      out.write("<!-- End Footer -->\n");
      out.write("\n");
      out.write("<!-- Back To Top -->\n");
      out.write("<a id=\"back-to-top\" href=\"#\">\n");
      out.write("\t<i class=\"font-icon-arrow-simple-up\"></i>\n");
      out.write("</a>\n");
      out.write("<!-- End Back to Top -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Js -->\n");
      out.write(" <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script> <!-- jQuery Core -->\n");
      out.write("<script src=\"_include/js/bootstrap.min.js\"></script> <!-- Bootstrap -->\n");
      out.write("<script src=\"_include/js/supersized.3.2.7.min.js\"></script> <!-- Slider -->\n");
      out.write("<script src=\"_include/js/waypoints.js\"></script> <!-- WayPoints -->\n");
      out.write("<script src=\"_include/js/waypoints-sticky.js\"></script> <!-- Waypoints for Header -->\n");
      out.write("<script src=\"_include/js/jquery.isotope.js\"></script> <!-- Isotope Filter -->\n");
      out.write("<script src=\"_include/js/jquery.fancybox.pack.js\"></script> <!-- Fancybox -->\n");
      out.write("<script src=\"_include/js/jquery.fancybox-media.js\"></script> <!-- Fancybox for Media -->\n");
      out.write("<script src=\"_include/js/plugins.js\"></script> <!-- Contains: jPreloader, jQuery Easing, jQuery ScrollTo, jQuery One Page Navi -->\n");
      out.write("<script src=\"_include/js/main.js\"></script> <!-- Default JS -->\n");
      out.write("<!-- End Js -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
