/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-12-15 00:13:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.File;
import board.dao.BoardDao;
import board.vo.BoardBean;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("board.dao.BoardDao");
    _jspx_imports_classes.add("board.vo.BoardBean");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');

	int pageno = Integer.parseInt(request.getParameter("pageno"));
	BoardDao dao = new BoardDao();
	BoardBean vo = new BoardBean();
	vo = dao.selectBoard(Integer.parseInt(request.getParameter("no")));
	//out.print(pageno);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.4.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/head.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"content\" id=\"content\">\r\n");
      out.write("\t\t<div class=\"viewForm\">\r\n");
      out.write("\t\t<div id=\"wrap\"> \r\n");
      out.write("\t<form>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t <div class=\"gallery-info\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<h2>Review View</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<div class=\"input-group\" align=\"left\">\r\n");
      out.write("\t\t<span class=\"input-group-addon\" class=\"form-control\" placeholder=\"username\" aria-describedby=\"sizing-addon1\"id=\"sizing-addon1\">등록자</span>\r\n");
      out.write("\t\t\t<input type=\"text\"  disabled=\"disabled\" class=\"form-control\" placeholder=\"username\" aria-describedby=\"sizing-addon1\" id=\"username\" name=\"username\" value=\"");
      out.print(vo.getUsername() );
      out.write("\">\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<div class=\"input-group\" align=\"left\">\r\n");
      out.write("\t\t<span class=\"input-group-addon\" id=\"sizing-addon2\">구분</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 
		if("00001".equals(vo.getCategory())){
			out.println("방후기");
		}else if("00002".equals(vo.getCategory())){
			out.println("서비스");
		}else if("00003".equals(vo.getCategory())){
			out.println("주변");
		}else if("00004".equals(vo.getCategory())){
			out.println("기타");
		}
		
      out.write("\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"input-group\" align=\"left\">\t\r\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"sizing-addon3\">제목</span>\r\n");
      out.write("\t\t\t<input type=\"text\"  disabled=\"disabled\" class=\"form-control\" placeholder=\"title\" aria-describedby=\"sizing-addon3\" id=\"title\" name=\"title\" value=\"");
      out.print( vo.getTitle() );
      out.write("\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"input-group\" align=\"left\">\r\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"sizing-addon4\">내용</span>\r\n");
      out.write("\t\t\t<textarea  disabled=\"disabled\" class=\"form-control\" placeholder=\"content\" aria-describedby=\"sizing-addon4\"  rows=\"15\" cols=\"75%\" name=\"content\"  id=\"content\" >");
      out.print(vo.getContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"input-group\" align=\"left\">\t\r\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"sizing-addon5\">이미지</span>\r\n");
      out.write("\t\t\t<img src=\"/pan/files/");
      out.print(vo.getFile_name() );
      out.write("\" width=\"100%\" height=\"300px\">\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"input-group\" align=\"left\">\r\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"sizing-addon6\">설명/다운로드</span>\r\n");
      out.write("\t\t\t<a href='/pan/Download?file=");
      out.print(vo.getFile_name() );
      out.write('\'');
      out.write('>');
      out.print(vo.getFile_name() );
      out.write("</a>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"button1\" value=\"수정\" onclick=\"location.href='/pan/board/upd.jsp?no=");
      out.print(vo.getNo());
      out.write("&pageno=");
      out.print(pageno);
      out.write("'\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"button1\" value=\"삭제\" onclick=\"location.href='/pan/board/del.jsp?no=");
      out.print(vo.getNo());
      out.write("&pageno=");
      out.print(pageno);
      out.write("'\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"button1\" name=\"버튼\" value=\"이전\" onclick=\"location.href='/pan/board/BoardServlet?command=board_list'\"/>\r\n");
      out.write("\t\t</center>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\t\t\r\n");
      out.write("</div></div></div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/foot.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
