/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-12-19 05:40:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<!--[if lt IE 7]><html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"ko\"> <![endif]-->\n");
      out.write("<!--[if (IE 7)&!(IEMobile)]><html class=\"no-js lt-ie9 lt-ie8\" lang=\"ko\"><![endif]-->\n");
      out.write("<!--[if (IE 8)&!(IEMobile)]><html class=\"no-js lt-ie9\" lang=\"ko\"><![endif]-->\n");
      out.write("<!--[if (IE 9)]><html class=\"no-js ie9\" lang=\"ko\"><![endif]-->\n");
      out.write("<!--[if gt IE 8]><!-->\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<!--<![endif]-->\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/myscript.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<script src=\"https://use.typekit.net/ehh4lya.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\tjQuery(function() {\n");
      out.write("\t\tjQuery('#camera_wrap_1').camera({\n");
      out.write("\t\t\ttransPeriod : 500,\n");
      out.write("\t\t\ttime : 3000,\n");
      out.write("\t\t\theight : '490px',\n");
      out.write("\t\t\tthumbnails : false,\n");
      out.write("\t\t\tpagination : true,\n");
      out.write("\t\t\tplayPause : false,\n");
      out.write("\t\t\tloader : false,\n");
      out.write("\t\t\tnavigation : false,\n");
      out.write("\t\t\thover : false\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\t<nav class=\"side\">\n");
      out.write("\t<div class=\"side__inner\">\n");
      out.write("\t\t<div class=\"top\">\n");
      out.write("\t\t\t<a href=\"#\">Home menu</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"bottom\">\n");
      out.write("\t\t\t<a href=\"http://blog.naver.com/ijuju88\">blog</a> <a\n");
      out.write("\t\t\t\thref=\"mailto:oxju88@gmail.com\">EMAIL ME</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<section class=\"section section--hello\" id=\"hello\">\n");
      out.write("\t<div class=\"section__inner\">\n");
      out.write("\t\t<div class=\"block\">\n");
      out.write("\t\t\t<a class=\"pre\" href=\"#intro\"><span>#0</span>Hello</a>\n");
      out.write("\t\t\t<h2>Ok Joo Jeon</h2>\n");
      out.write("\t\t\t<ul class=\"anchornav\">\n");
      out.write("\t\t\t\t<li><a href=\"#intro\">Intro <span>#1 Intro</span></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#about\">About <span>#2 자기소개</span></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#clients\">Study<span>#3 학습현황</span></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#portfolio\">Portfolio <span>#4 포트폴리오</span></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#contact\">Contact <span>#5 Contact</span></a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"section section--intro\" id=\"intro\">\n");
      out.write("\t<div class=\"section__inner\">\n");
      out.write("\t\t<div class=\"block\">\n");
      out.write("\t\t\t<a class=\"pre\" href=\"#intro\"><span>#1</span>Intro</a>\n");
      out.write("\t\t\t<h1>intro</h1>\n");
      out.write("\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t내일을 위해 준비하는 성실한 직업학교 교육생\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"section section--about\" id=\"about\"> <svg\n");
      out.write("\t\txmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 10\"\n");
      out.write("\t\tpreserveAspectRatio=\"none\"> <polygon points=\"100 0 100 10 0 10\" />\n");
      out.write("\t</svg>\n");
      out.write("\n");
      out.write("\t<div class=\"section__inner\">\n");
      out.write("\t\t<div class=\"block\">\n");
      out.write("\t\t\t<a class=\"pre\" href=\"#about\"><span>#2</span>자기소개</a>\n");
      out.write("\t\t\t<h2>성실과 노력</h2>\n");
      out.write("\t\t\t<p class=\"lead\">아직까지는 어려운것이 많지만 굴하지 않고 그럴수록 노력해서 새로운것을 배워나가고 있습니다. \n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"section section--clients\" id=\"clients\"> <svg\n");
      out.write("\t\txmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 10\"\n");
      out.write("\t\tpreserveAspectRatio=\"none\"> <polygon points=\"100 10 0 0 0 10\" />\n");
      out.write("\t</svg>\n");
      out.write("\n");
      out.write("\t<div class=\"section__inner\">\n");
      out.write("\t\t<div class=\"block\">\n");
      out.write("\t\t\t<a class=\"pre\" href=\"#clients\"><span>#3</span>학습현황</a>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-md-3 bar\">\n");
      out.write("\t\t\t\t<div class=\"progB chart\" data-percent=\"70\" data-animate=\"3500\">\n");
      out.write("\t\t\t\t\t<div class=\"chart chart-content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"percentage\" data-percent=\"70\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"percent\">70</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"textP\">\n");
      out.write("\t\t\t\t\t<h3>Java</h3>\n");
      out.write("\t\t\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t\t\t어떤언어든 들어가면 들어갈수록<br />\n");
      out.write("\t\t\t\t\t\t빙산의 일각이라는 생각이 듭니다.\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-3 bar\">\n");
      out.write("\t\t\t\t<div class=\"progB chart\" data-percent=\"60\" data-animate=\"3500\">\n");
      out.write("\t\t\t\t\t<div class=\"chart chart-content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"percentage\" data-percent=\"60\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"percent\">60</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"textP\">\n");
      out.write("\t\t\t\t\t<h3>웹</h3>\n");
      out.write("\t\t\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t\t\tHTML5, Jquery, JavaScript등의 기본기능구현 <br />\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-3 bar \">\n");
      out.write("\t\t\t\t<div class=\"progB chart\" data-percent=\"70\" data-animate=\"3500\">\n");
      out.write("\t\t\t\t\t<div class=\"chart chart-content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"percentage\" data-percent=\"70\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"percent\">70</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"textP\">\n");
      out.write("\t\t\t\t\t<h3>jsp</h3>\n");
      out.write("\t\t\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t\t\tjsp의 기본기능구현 및 <br />간단한게시판작성가능\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-3 bar \">\n");
      out.write("\t\t\t\t<div class=\"progB chart\" data-percent=\"50\" data-animate=\"3500\">\n");
      out.write("\t\t\t\t\t<div class=\"chart chart-content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"percentage\" data-percent=\"50\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"percent\">50</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"textP\">\n");
      out.write("\t\t\t\t\t<h3>android</h3>\n");
      out.write("\t\t\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t\t\t준비중입니다.<br />\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div></div></div>\n");
      out.write("\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"section section--portfolio1\" id=\"portfolio\">\n");
      out.write("\t<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\"\n");
      out.write("\t\tpreserveAspectRatio=\"none\"> <path\n");
      out.write("\t\td=\"M0 100 C 20 0 50 0 100 100 Z\"></path> </svg>\n");
      out.write("\n");
      out.write("\t<div class=\"section__inner\">\n");
      out.write("\t\t<div class=\"block\">\n");
      out.write("\t\t\t<a class=\"pre\" href=\"#portfolio\"><span>#4</span>Portfolio</a>\n");
      out.write("\t\t\t<h2>java(세금)계산서 #1</h2>\n");
      out.write("\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t<a href=\"http://blog.naver.com/ijuju88/220843915979\">블로그참고</a></br>\n");
      out.write("\t\t\tSwing과 poi라이브러리를 활용한 (세금)계산서 프로그램입니다.</br></br>\n");
      out.write("\t\t\t주요기능▼</br>\n");
      out.write("\t\t\t공급(받는)자 만들기, (세금)계산서 작성, 검색, poi라이브러리를 이용한 엑셀저장</br></br>\n");
      out.write("\t\t\t구현기능▼</br>\n");
      out.write("\t\t\t(세금)계산서작성, poi라이브러리 부분</br>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<section class=\"section section--portfolio\" id=\"portfolio2\">\n");
      out.write("\t<div class=\"section__inner\">\n");
      out.write("\t\t<div class=\"block\">\n");
      out.write("\t\t\t<h2>JSP 펜션사이트 #2</h2>\n");
      out.write("\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t편션소개및 예약 사이트입니다.</br></br>\n");
      out.write("\t\t\t주요기능▼</br>\n");
      out.write("\t\t\t<a href=\"http://ijuju88.cafe24.com/pan/admin/index.jsp\">관리자</a> : 검색(회원,예약), 방정보, 성수기/계좌수정, 공지게시판 등</br>\n");
      out.write("\t\t\t<a href=\"http://ijuju88.cafe24.com/pan/loc.jsp\">사용자</a> : 객실소개(lightbox이용), 예약및 확인, 게시판(공지, 문의, 리뷰) 등\n");
      out.write("\t\t\t</br></br>\n");
      out.write("\t\t\t구현기능▼(코드구현부분담당)</br>\n");
      out.write("\t\t\t관리자 - 방정보, 검색부분(예약검색 입금완료부분 포함)</br>\n");
      out.write("\t\t\t사용자 - 예약관련, 리뷰게시판\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" width=\"100%\"\n");
      out.write("\t\theight=\"100\" viewBox=\"0 0 100 102\" preserveAspectRatio=\"none\"\n");
      out.write("\t\tclass=\"bottom\"> <path d=\"M0 0 L50 100 L100 0 Z\"></path> </svg> </section>\n");
      out.write("\n");
      out.write("\t<section class=\"section section--portfolio2\" id=\"portfolio3\">\n");
      out.write("\t<div class=\"section__inner\">\n");
      out.write("\t\t<div class=\"blue\">\n");
      out.write("\t\t\t<h2>안드로이드 #3</h2>\n");
      out.write("\t\t\t<p class=\"lead\">준비중입니다</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" width=\"100%\"\n");
      out.write("\t\theight=\"100\" viewBox=\"0 0 100 102\" preserveAspectRatio=\"none\"\n");
      out.write("\t\tclass=\"bottom\"> <path d=\"M0 0 L50 100 L100 0 Z\"></path> </svg> </section>\n");
      out.write("\n");
      out.write("\t<section class=\"section section--contact\" id=\"contact\">\n");
      out.write("\t<div class=\"section__inner\">\n");
      out.write("\t\t<div class=\"block\">\n");
      out.write("\t\t\t <a class=\"pre\" href=\"#contact\"><span>#5</span>Contact</a>\n");
      out.write("            <h2>자세한 사항은</h2></br>\n");
      out.write("            <p class=\"lead\">\n");
      out.write("            <a href=\"mailto:oxju88@gmail.com\">이메일</a>\n");
      out.write("            이나, <a href=\"http://blog.naver.com/ijuju88\">블로그</a>를 참고해주세요.</p>\n");
      out.write("        </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
