/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-12-14 23:55:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/ijuju/test/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/pan/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/ijuju/test/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/pan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1478178682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>hotel</title>\r\n");
      out.write("<script src=\"../Main/js/pop.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/head.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"content\" id=\"content\">\r\n");
      out.write("\t\t<div class=\"Welcome-section\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h2>Welcome to hotel</h2>\r\n");
      out.write("\t\t\t\t<div class=\"Welcome-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 welcome-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"welcome-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/w1.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h4>조식</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>저희 리조트에서는 조식에 속을 편한하게 할 전복죽 등 간단한 한식 뷔페가 준비되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 welcome-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"welcome-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/w2.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h4>다양한 체험</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>저희 리조트에서는 제주도 특산품인 녹차, 감귤류, 화산송이를 이용한 \r\n");
      out.write("\t\t\t\t\t\t비누만들기 체험이 준비되어 있습니다.\r\n");
      out.write("\t\t\t\t\t\t사랑하는 가족, 연인들과 같이 체험하실 수 있습니다.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 welcome-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"welcome-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/w3.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h4>특별한 장소</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>저희 리조트에서는 주변에 바다전망대와 올레7코스,\r\n");
      out.write("\t\t\t\t\t\t 섬등 빼어난 자연 경관을 자랑합니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--Welcome-->\r\n");
      out.write("\t\t<div class=\"features\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h3>features</h3>\r\n");
      out.write("\t\t\t\t<div class=\"features-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 feature-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-gift\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>이용안내</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature2\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../Main/images/list-arrow.png\" alt=\"\" />체크인 15:00 부터 / 체크와웃 11:00 까지\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><img src=\"../Main/images/list-arrow.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t레스토랑 무료 조식 - 07:00 ~ 10:00\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><img src=\"../Main/images/list-arrow.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t부대시설 - 야외 바베규시설<br>(이용료 15000원, 사전 문의)\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><img src=\"../Main/images/list-arrow.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t비치품 - 기본 목욕용품, 올래 GIRA 와이파이, tv, 에어컨 ......\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 feature-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>취소수수료</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>7일전 : 10%<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t6일~5일전 : 30%<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t4~3일전 : 50%<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t2~1일전 : 80%<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t당일 : 환불안됨<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t천재지변등 : 전액환불<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 feature-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-camera\" aria-hidden=\"true\" onclick=\"javascript:location.href='../../pan/Room/gallery.jsp';\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>외부전경</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><img src=\"../Main/images/list-arrow.png\" alt=\"\" />외부전경 갤러리입니다<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t 카메라 아이콘을 클릭해주세요\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><br><br></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 feature-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-calendar\" aria-hidden=\"true\" onclick=\"javascript:location.href='../Room/about.jsp';\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>소개</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><img src=\"../Main/images/list-arrow.png\" alt=\"\" />소개, 수상내역을 볼수 있습니다<br><br><br><br></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- slider -->\r\n");
      out.write("\t\t<div class=\"slider1\">\r\n");
      out.write("\t\t\t<div class=\"arrival-grids\">\r\n");
      out.write("\t\t\t\t<ul id=\"flexiselDemo1\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:location.href=('.../../pan/Room/Room1.jsp');\"><img src=\"images/d2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:location.href=('../../pan/Room/Room1.jsp');\"><img src=\"images/d4.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:location.href=('../../pan/Room/Room1.jsp');\"><img src=\"images/d6.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:location.href=('../../pan/Room/Room2.jsp');\"><img src=\"images/s2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:location.href=('../../pan/Room/Room2.jsp');\"><img src=\"images/s4.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:location.href=('../../pan/Room/Room2.jsp');\"><img src=\"images/s5.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:location.href=('../../pan/Room/Room3.jsp');\"><img src=\"images/h1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:location.href=('../../pan/Room/Room3.jsp');\"><img src=\"images/h2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#flexiselDemo1\").flexisel({\r\n");
      out.write("\t\t\t\t\t\t\tvisibleItems : 4,\r\n");
      out.write("\t\t\t\t\t\t\tanimationSpeed : 1000,\r\n");
      out.write("\t\t\t\t\t\t\tautoPlay : true,\r\n");
      out.write("\t\t\t\t\t\t\tautoPlaySpeed : 3000,\r\n");
      out.write("\t\t\t\t\t\t\tpauseOnHover : true,\r\n");
      out.write("\t\t\t\t\t\t\tenableResponsiveBreakpoints : true,\r\n");
      out.write("\t\t\t\t\t\t\tresponsiveBreakpoints : {\r\n");
      out.write("\t\t\t\t\t\t\t\tportrait : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tchangePoint : 480,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvisibleItems : 1\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tlandscape : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tchangePoint : 640,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvisibleItems : 2\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\ttablet : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tchangePoint : 768,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvisibleItems : 3\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //slider -->\r\n");
      out.write("\t\t<!--most-popular-->\r\n");
      out.write("\t\t<div class=\"most-popular\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"popular-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 popular-grid\">\r\n");
      out.write("\t\t\t\t\t\t<h3>인기있는 정보</h3>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">RESTAURANTS & BARS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">WEDDINGS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">USEFUL ADVICE</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">PRIVATE DINING & CELEBRATIONS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">HEALTH & FITNESS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">HOTEL PHOTOS & VIDEOS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">CAR RENTALS</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7 popular-grid1\">\r\n");
      out.write("\t\t\t\t\t\t<h3>회원평가</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>2016년 00월 00일 가족들과 같이 000리조트에 놀려갔어요.\r\n");
      out.write("\t\t\t\t\t\t오자마자 바다와 섬이 보여서 아름다웠어요. 인포에 있는 사람들들도 친절하고\r\n");
      out.write("\t\t\t\t\t\t방도 깨끗했어요. </p>\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">0000</a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p>저녁에 바베큐 먹었는데 밖에서 구워먹을 수 있어서 엄청 좋았어요.\r\n");
      out.write("\t\t\t\t\t\t주위에 자연경관이 얼마나 좋던지 올레코스도 있고 바다전망대도 가고 000리조트 앞으로도 \r\n");
      out.write("\t\t\t\t\t\t좋은 리조트로 남았으면 좋겠어요</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">0000</a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/foot.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
