/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-12-15 00:10:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Room;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class services_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Services</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/head.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<div class=\"services\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"services-main\">\r\n");
      out.write("\t\t\t\t\t<h2>services</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"services1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 services-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-5 serv-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../Main/images/p2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7 serv-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>카페</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>저희 리조트에서는 카페가 있습니다. 지팡이 아이스크림을 비롯해 빵과 커피 등을 제공합니다</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 services-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-5 serv-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../Main/images/p3.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7 serv-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>바베큐</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>저희 지조트에서는 테라스에서 바베큐요리를 즐길수 있는 시설이 준비되어있습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t삼겹살, 조개등을 즐겨보세요.\r\n");
      out.write("\t\t\t\t\t\t\t\t(오시기 전에 문의바랍니다 이용료 15000원)</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"services2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 services-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-5 serv-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../Main/images/w2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7 serv-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>수제비누만들기 체험</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>저희 호텔에서는 제주도 특산품인 녹차, 감귤류, 화산송이를 이용한 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t비누만들기 체험이 준비되어 있습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t사랑하는 가족, 연인들과 같이 체험하실 수 있습니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 services-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-5 serv-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../Main/images/o1.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7 serv-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>자연경관</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>저희 호텔에서는 주변에 바다전망대와 올레7코스,\r\n");
      out.write("\t\t\t\t\t\t\t\t 섬등 빼어난 자연 경관을 자랑합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<<div class=\"features\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h3>features</h3>\r\n");
      out.write("\t\t\t\t<div class=\"features-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 feature-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-gift\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>이용안내</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature2\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../Main/images/list-arrow.png\" alt=\"\" />체크인 15:00 부터 / 체크와웃 11:00 까지\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><img src=\"../Main/images/list-arrow.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t레스토랑 무료 조식 - 07:00 ~ 10:00\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><img src=\"../Main/images/list-arrow.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t부대시설 - 야외 바베규시설<br>(이용료 15000원, 사전 문의)\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><img src=\"../Main/images/list-arrow.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t비치품 - 기본 목욕용품, 올래 GIRA 와이파이, tv, 에어컨 ......\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 feature-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>취소수수료</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>7일전 : 10%<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t6일~5일전 : 30%<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t4~3일전 : 50%<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t2~1일전 : 80%<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t당일 : 환불안됨<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t천재지변등 : 전액환불<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 feature-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-camera\" aria-hidden=\"true\" onclick=\"javascript:location.href='../Room/gallery.jsp';\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>외부전경</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><img src=\"../Main/images/list-arrow.png\" alt=\"\" />외부전경 갤러리입니다<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t 카메라 아이콘을 클릭해주세요\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><br><br></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 feature-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-calendar\" aria-hidden=\"true\" onclick=\"javascript:location.href='../Room/about.jsp';\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>소개</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feature2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><img src=\"../Main/images/list-arrow.png\" alt=\"\" />소개, 수상내역을 볼수 있습니다<br><br><br><br></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"packages-section\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h3>our packages</h3>\r\n");
      out.write("\t\t\t\t<div class=\"packages-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 packages-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"packages-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../Main/images/p6.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h4>cubilia curae</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>quis autem</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 packages-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"packages-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../Main/images/p7.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h4>diam eu massa</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>quis autem</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 packages-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"packages-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../Main/images/p8.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h4>cubilia curae</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>quis autem</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 packages-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"packages-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../Main/images/p9.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h4>diam eu massa</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>quis autem</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/foot.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
